In [ ]:
import pandas as pd

In [ ]:
#conjunto de datos
datos= {
    "usuario": ["Ana","Luis","Martha","Carolina","Sofia","Pedro","Elena","Diego"],
    "edad": [22,33,28,40,19,31,26,45],
    "ciudad": ["CDMX","Monterrey","Guadalajara", "Puebla","Cancun", "Merida","Tijuana","toluca"],
    "compras_realizadas": [5,12,3,29,1,7,4,15],
    "activo": [True,False,True,True,False,True,True,False],
    "fecha_registro":["2026-02-10","2026-01-19","2026-02-19","2026-01-05","2026-02-03","2026-04-02","2026-09-12","2026-04-05"]
}

In [3]:
df=pd.DataFrame(datos)
df

    usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0       Ana    22         CDMX                   5    True     2026-02-10
1      Luis    33    Monterrey                  12   False     2026-01-19
2    Martha    28  Guadalajara                   3    True     2026-02-19
3  Carolina    40       Puebla                  29    True     2026-01-05
4     Sofia    19       Cancun                   1   False     2026-02-03
5     Pedro    31       Merida                   7    True     2026-04-02
6     Elena    26      Tijuana                   4    True     2026-09-12
7     Diego    45       toluca                  15   False     2026-04-05

In [4]:
df.head()

    usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0       Ana    22         CDMX                   5    True     2026-02-10
1      Luis    33    Monterrey                  12   False     2026-01-19
2    Martha    28  Guadalajara                   3    True     2026-02-19
3  Carolina    40       Puebla                  29    True     2026-01-05
4     Sofia    19       Cancun                   1   False     2026-02-03

In [ ]:
cantidad= 100000

In [6]:
import random

In [8]:
nombres=  ["Ana","Luis","Martha","Carolina","Sofia","Pedro","Elena","Diego"]
ciudades = ["CDMX","Monterrey","Guadalajara", "Puebla","Cancun", "Merida","Tijuana","toluca"]
categorias = ["Tecnologia","Ropa","Hogar","Videojuegos","Deportes","Calzado","Limpieza","verano"]

In [9]:
dfMillon= pd.DataFrame({
    "nombre": [random.choice(nombres) for _ in range(cantidad) ],
    "edad": (random.randint(18,65) for _ in range(cantidad)),
    "ciudad": [random.choice(ciudades) for _ in range(cantidad)],
    "categoria": [random.choice(categorias) for _ in range(cantidad)],
})

In [12]:
df.memory_usage(deep=True)

Index                 132
usuario               433
edad                   64
ciudad                447
compras_realizadas     64
activo                  8
fecha_registro        472
dtype: int64